WIP: Discoint scraper
Urigo/accounter-fullstack pull request #1545
Opened 2024-12-24 15:25 UTC by elie222

Based off of:
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/discount.ts

2025-01-08 13:06 UTC, elie222 commented
This is ready to be merged. Just have one question about branch numbers that I sent Gil on DM

2025-01-12 13:39 UTC, gilgardosh commented on packages/modern-poalim-scraper/src/scrapers/types/discount/get-account.ts
> +export const getAccountSchema = z.object({
Does Zod validate if new attributes were added to the object?

2025-01-12 15:13 UTC, gilgardosh requested changes

2025-01-12 15:13 UTC, gilgardosh commented on packages/migrations/src/actions/2024-12-26T12-15-43.bank-discount.ts
> +import { type MigrationExecutor } from '../pg-migrator.js';
Requires some updates, as discussed personally

2025-01-12 15:29 UTC, gilgardosh approved these changes

2025-01-12 15:30 UTC, merged